services:
  - type: web
    name: taxteamwork-python-service
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
